server:
  port: 8080

spring:
  application:
    name: smartspend-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rajeshvamsi143
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: mock-key-for-dev
      chat:
        options:
          model: gpt-4o-mini